#!/bin/sh

# Get battery percentage and state
battery_path="/org/freedesktop/UPower/devices/battery_BAT1"
bat=$(upower -i $battery_path | grep percentage | sed 's/ *percentage: *//g' | sed 's/%//')
state=$(upower -i $battery_path | grep state | sed 's/ *state: *//')

# Define icons for different ranges of battery percentage
charging_icons="󰢜 󰂆 󰂇 󰢝 󰂉 󰂉 󰢞 󰂊 󰂋 󰂅"
discharging_icons="󰁺 󰁻 󰁼 󰁽 󰁾 󰁿 󰂀 󰂁 󰂂 󰁹"

# Determine which set of icons to use
if [ "$state" = "charging" ] || [ "$state" = "fully-charged" ]; then
  icons=$charging_icons
else
  icons=$discharging_icons
fi

# Convert icons string to array-like handling
icon_array=$(echo $icons | tr ' ' '\n')

# Calculate icon index based on battery percentage
index=$((bat / 10))
icon=$(echo "$icon_array" | sed -n "$((index + 1))p")

# Print the selected icon and battery percentage
echo -n "$icon $bat%"
