#!/bin/sh

if [ $(pactl list sources | grep -q "Mute: yes" && echo "yes" || echo "no") = "no" ]; then
  echo -n "  󰍬 " && dunstify -t 1000 -u low -i audio-volume-medium "Mic Unmuted" -h string:x-dunst-stack-tag:volume -h string:x-dunst-stack-mode:replace
else
  echo -n "" && dunstify -t 1000 -u low -i audio-volume-muted "Mic Muted" -h string:x-dunst-stack-tag:volume -h string:x-dunst-stack-mode:replace
fi
