#!/bin/sh

if pactl list sources | grep -q "Mute: yes"; then
  notify-send " Mic Muted" -t 1000 -u low -c "osd-text" --hint=string:x-dunst-stack-tag:osd
else
  echo -n "  󰍬 "
  notify-send " Mic Unmuted" -t 1000 -u low -c "osd-text" --hint=string:x-dunst-stack-tag:osd
fi
