#!/bin/sh

current=$(echo $1 | sed 's/%//')

if [ $current -le 10 ]; then
  echo -n $2
elif [ $current -le 20 ]; then
  echo -n $3
elif [ $current -le 30 ]; then
  echo -n $4
elif [ $current -le 40 ]; then
  echo -n $5
elif [ $current -le 50 ]; then
  echo -n $6
elif [ $current -le 60 ]; then
  echo -n $7
elif [ $current -le 70 ]; then
  echo -n $8
elif [ $current -le 80 ]; then
  echo -n $9
elif [ $current -le 90 ]; then
  echo -n ${10}
else
  echo -n ${11}
fi
