#!/bin/sh
vol_info=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
vol=$(echo "$vol_info" | awk '{print $2 * 100}')
mute=$(echo "$vol_info" | awk '{print $3}')

if [ "$mute" = "[MUTED]" ]; then
  echo -n "  󰖁" && notify-send " Volume Muted" -t 500 -u low -c "osd-text"
else
  if [ "$vol" -le 33 ]; then
    icon="󰕿"
  elif [ "$vol" -le 66 ]; then
    icon="󰖀"
  else
    icon="󰕾"
  fi

  echo -n "  $icon" && notify-send " 󰕾" -t 500 -u low -h int:value:$vol -c "osd"
fi
