#!/bin/sh

vol=$(pactl list sinks | grep 'Volume:' | head -n 1 | awk '{print $5}' | sed 's/%//')

if [ $(pactl list sinks | grep "Mute:" | awk '{print $2}') = "yes" ]; then
  echo -n "ﱝ"
else
  if [ "$vol" -le 33 ]; then
    icon="󰕿"
  elif [ "$vol" -le 66 ]; then
    icon="奔"
  else
    icon="󰕾"
  fi
  echo -n "$icon"
fi
