#!/bin/sh

strength=$(awk '/wlan0/ { print int(($3) * 100 / 70) }' /proc/net/wireless)

if [ -n "$strength" ]; then
  if [ "$strength" -le 25 ]; then
    icon="󰤟"
  elif [ "$strength" -le 50 ]; then
    icon="󰤢"
  elif [ "$strength" -le 75 ]; then
    icon="󰤥"
  else
    icon="󰤨"
  fi
else
  icon="󰤮"
fi

echo -n "$icon"
