#!/bin/sh

strength=$(iw dev wlo1 link | grep signal | awk '{d=$2; p=2*(d+100); if(p>100) p=100; if(p<0) p=0; printf("%.0f\n", p)}')

if [ -n "$strength" ]; then
  if [ "$strength" -le 25 ]; then
    icon="󰤟"
  elif [ "$strength" -le 50 ]; then
    icon="󰤢"
  elif [ "$strength" -le 75 ]; then
    icon="󰤥"
  else
    icon="󰤨"
  fi
else
  icon="󰤮"
fi

echo -n "$icon"
