#!/bin/sh

if grep -q 'wlan0' /proc/net/wireless; then
  strength=$(awk '/wlan0/ { print int(($3) * 100 / 70) }' /proc/net/wireless)
  echo -n "$(/home/daniel/mis_repos/someblocks/blocks/percentage $strength 󰤟 󰤢 󰤢 󰤨)  $strength%"
else
  echo -n "󰤮  Wi-Fi off"
fi
